[build-system]
requires = ["setuptools>=83.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = []

[project]
name = "django-playground"
version = "0.1.0"
description = "A place for me to try various things with a Django Site"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.1.1",
    "django-environ>=0.14.0",
    "django-health-check>=4.5.1",
    "gunicorn>=26.2.0",
    "neapolitan>=26.1",
    "psycopg[binary,pool]>=3.3.5",
    "whitenoise>=6.8.0",
]

[dependency-groups]
dev = [
    "django-debug-toolbar>=8.0.0",
    "django-upgrade>=1.32.0",
    "prek>=0.5.2",
    "pytest-cov>=7.1.0",
    "pytest-django>=4.14.0",
    "pytest-randomly>=5.0.0",
    "pytest-xdist>=3.8.0",
    "ruff>=0.16.6",
    "ty>=0.0.78",
    "zizmor>=1.30.0",
]
