# Generated by Django 6.1.1 on 2026-09-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_navigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='active',
            field=models.BooleanField(null=True),
        ),
    ]
