# Generated by Django 6.1.1 on 2026-09-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_navigation_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='navigation_order',
            field=models.IntegerField(null=True),
        ),
    ]
