# Generated by Django 6.1.1 on 2026-09-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_navigation_navigation_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='authenticated_user_required',
            field=models.BooleanField(default=False),
        ),
    ]
